In [1]:
#Q1A

for i in range (1, 101):
    if i%3==0 and i%5!=0:
        print ("Mickey")
    elif i%5==0 and i%3!=0:
        print ("Mouse")
    elif i%3==0 and i%5==0:
        print ("MickeyMouse")
    else:
        print (i)

1
2
Mickey
4
Mouse
Mickey
7
8
Mickey
Mouse
11
Mickey
13
14
MickeyMouse
16
17
Mickey
19
Mouse
Mickey
22
23
Mickey
Mouse
26
Mickey
28
29
MickeyMouse
31
32
Mickey
34
Mouse
Mickey
37
38
Mickey
Mouse
41
Mickey
43
44
MickeyMouse
46
47
Mickey
49
Mouse
Mickey
52
53
Mickey
Mouse
56
Mickey
58
59
MickeyMouse
61
62
Mickey
64
Mouse
Mickey
67
68
Mickey
Mouse
71
Mickey
73
74
MickeyMouse
76
77
Mickey
79
Mouse
Mickey
82
83
Mickey
Mouse
86
Mickey
88
89
MickeyMouse
91
92
Mickey
94
Mouse
Mickey
97
98
Mickey
Mouse

In [2]:
#Q1B

A=[]
for i in range (1, 101):
    if i%3==0 and i%5!=0:
        A.append("Mickey")
    elif i%5==0 and i%3!=0:
        A.append("Mouse")
    elif i%3==0 and i%5==0:
        A.append("MickeyMouse")
    else:
        A.append(i)
print(A)

for i in range (len(A)):
    if A[i]=="Mickey":
        A[i]="Donald"
    elif A[i]=="Mouse":
        A[i]="Duck"
print(tuple(A))

[1, 2, 'Mickey', 4, 'Mouse', 'Mickey', 7, 8, 'Mickey', 'Mouse', 11, 'Mickey', 13, 14, 'MickeyMouse', 16, 17, 'Mickey', 19, 'Mouse', 'Mickey', 22, 23, 'Mickey', 'Mouse', 26, 'Mickey', 28, 29, 'MickeyMouse', 31, 32, 'Mickey', 34, 'Mouse', 'Mickey', 37, 38, 'Mickey', 'Mouse', 41, 'Mickey', 43, 44, 'MickeyMouse', 46, 47, 'Mickey', 49, 'Mouse', 'Mickey', 52, 53, 'Mickey', 'Mouse', 56, 'Mickey', 58, 59, 'MickeyMouse', 61, 62, 'Mickey', 64, 'Mouse', 'Mickey', 67, 68, 'Mickey', 'Mouse', 71, 'Mickey', 73, 74, 'MickeyMouse', 76, 77, 'Mickey', 79, 'Mouse', 'Mickey', 82, 83, 'Mickey', 'Mouse', 86, 'Mickey', 88, 89, 'MickeyMouse', 91, 92, 'Mickey', 94, 'Mouse', 'Mickey', 97, 98, 'Mickey', 'Mouse']
(1, 2, 'Donald', 4, 'Duck', 'Donald', 7, 8, 'Donald', 'Duck', 11, 'Donald', 13, 14, 'MickeyMouse', 16, 17, 'Donald', 19, 'Duck', 'Donald', 22, 23, 'Donald', 'Duck', 26, 'Donald', 28, 29, 'MickeyMouse', 31, 32, 'Donald', 34, 'Duck', 'Donald', 37, 38, 'Donald', 'Duck', 41, 'Donald', 43, 44, 'MickeyMouse', 46, 47, 'Donald', 49, 'Duck', 'Donald', 52, 53, 'Donald', 'Duck', 56, 'Donald', 58, 59, 'MickeyMouse', 61, 62, 'Donald', 64, 'Duck', 'Donald', 67, 68, 'Donald', 'Duck', 71, 'Donald', 73, 74, 'MickeyMouse', 76, 77, 'Donald', 79, 'Duck', 'Donald', 82, 83, 'Donald', 'Duck', 86, 'Donald', 88, 89, 'MickeyMouse', 91, 92, 'Donald', 94, 'Duck', 'Donald', 97, 98, 'Donald', 'Duck')

In [3]:
#Q2

def swap (a, b):
    x=b
    y=a
    return x, y
swap(6,7)

(7, 6)

In [4]:
#Q3

from math import sqrt
def distance(x1, y1, x2, y2):
    U=(x1, y1)
    V=(x2, y2)
    c=(x1-x2)**2
    d=(y1-y2)**2

    dis=sqrt(c+d)
    print("The distance of two point is:",dis)
distance(3,0,0,4)

The distance of two point is: 5.0

In [15]:
#Q4

My_string="Write a program that prints the numbers from 1 to 100. \
But for multiples of three print Mickey instead of the number and for the multiples of five print Mouse. \
For numbers which are multiples of both three and five print MickeyMouse"
My_new_string=My_string.lower()
A=My_new_string
for i in A: 
    print( "the number of",i , My_new_string.count(i))

the number of w 2
the number of r 17
the number of i 14
the number of t 19
the number of e 22
the number of   41
the number of a 7
the number of   41
the number of p 8
the number of r 17
the number of o 13
the number of g 1
the number of r 17
the number of a 7
the number of m 12
the number of   41
the number of t 19
the number of h 9
the number of a 7
the number of t 19
the number of   41
the number of p 8
the number of r 17
the number of i 14
the number of n 10
the number of t 19
the number of s 9
the number of   41
the number of t 19
the number of h 9
the number of e 22
the number of   41
the number of n 10
the number of u 9
the number of m 12
the number of b 5
the number of e 22
the number of r 17
the number of s 9
the number of   41
the number of f 10
the number of r 17
the number of o 13
the number of m 12
the number of   41
the number of 1 2
the number of   41
the number of t 19
the number of o 13
the number of   41
the number of 1 2
the number of 0 2
the number of 0 2
the number of . 2
the number of   41
the number of b 5
the number of u 9
the number of t 19
the number of   41
the number of f 10
the number of o 13
the number of r 17
the number of   41
the number of m 12
the number of u 9
the number of l 6
the number of t 19
the number of i 14
the number of p 8
the number of l 6
the number of e 22
the number of s 9
the number of   41
the number of o 13
the number of f 10
the number of   41
the number of t 19
the number of h 9
the number of r 17
the number of e 22
the number of e 22
the number of   41
the number of p 8
the number of r 17
the number of i 14
the number of n 10
the number of t 19
the number of   41
the number of m 12
the number of i 14
the number of c 3
the number of k 2
the number of e 22
the number of y 2
the number of   41
the number of i 14
the number of n 10
the number of s 9
the number of t 19
the number of e 22
the number of a 7
the number of d 3
the number of   41
the number of o 13
the number of f 10
the number of   41
the number of t 19
the number of h 9
the number of e 22
the number of   41
the number of n 10
the number of u 9
the number of m 12
the number of b 5
the number of e 22
the number of r 17
the number of   41
the number of a 7
the number of n 10
the number of d 3
the number of   41
the number of f 10
the number of o 13
the number of r 17
the number of   41
the number of t 19
the number of h 9
the number of e 22
the number of   41
the number of m 12
the number of u 9
the number of l 6
the number of t 19
the number of i 14
the number of p 8
the number of l 6
the number of e 22
the number of s 9
the number of   41
the number of o 13
the number of f 10
the number of   41
the number of f 10
the number of i 14
the number of v 2
the number of e 22
the number of   41
the number of p 8
the number of r 17
the number of i 14
the number of n 10
the number of t 19
the number of   41
the number of m 12
the number of o 13
the number of u 9
the number of s 9
the number of e 22
the number of . 2
the number of   41
the number of f 10
the number of o 13
the number of r 17
the number of   41
the number of n 10
the number of u 9
the number of m 12
the number of b 5
the number of e 22
the number of r 17
the number of s 9
the number of   41
the number of w 2
the number of h 9
the number of i 14
the number of c 3
the number of h 9
the number of   41
the number of a 7
the number of r 17
the number of e 22
the number of   41
the number of m 12
the number of u 9
the number of l 6
the number of t 19
the number of i 14
the number of p 8
the number of l 6
the number of e 22
the number of s 9
the number of   41
the number of o 13
the number of f 10
the number of   41
the number of b 5
the number of o 13
the number of t 19
the number of h 9
the number of   41
the number of t 19
the number of h 9
the number of r 17
the number of e 22
the number of e 22
the number of   41
the number of a 7
the number of n 10
the number of d 3
the number of   41
the number of f 10
the number of i 14
the number of v 2
the number of e 22
the number of   41
the number of p 8
the number of r 17
the number of i 14
the number of n 10
the number of t 19
the number of   41
the number of m 12
the number of i 14
the number of c 3
the number of k 2
the number of e 22
the number of y 2
the number of m 12
the number of o 13
the number of u 9
the number of s 9
the number of e 22

In [8]:
#Q5

l = [36, 45, 58, 3, 74, 96, 64, 45, 31, 10, 24, 19, 33, 86, 99, 18, 63, 70, 85,
 85, 63, 47, 56, 42, 70, 84, 88, 55, 20, 54, 8, 56, 51, 79, 81, 57, 37, 91,
 1, 84, 84, 36, 66, 9, 89, 50, 42, 91, 50, 95, 90, 98, 39, 16, 82, 31, 92, 41,
 45, 30, 66, 70, 34, 85, 94, 5, 3, 36, 72, 91, 84, 34, 87, 75, 53, 51, 20, 89, 51, 20]
count=0
for i in l:
    count=l.count(i)
    if count==1:
        print("the number",i, "is unique")
        count=count+1

the number 58 is unique
the number 74 is unique
the number 96 is unique
the number 64 is unique
the number 10 is unique
the number 24 is unique
the number 19 is unique
the number 33 is unique
the number 86 is unique
the number 99 is unique
the number 18 is unique
the number 47 is unique
the number 88 is unique
the number 55 is unique
the number 54 is unique
the number 8 is unique
the number 79 is unique
the number 81 is unique
the number 57 is unique
the number 37 is unique
the number 1 is unique
the number 9 is unique
the number 95 is unique
the number 90 is unique
the number 98 is unique
the number 39 is unique
the number 16 is unique
the number 82 is unique
the number 92 is unique
the number 41 is unique
the number 30 is unique
the number 94 is unique
the number 5 is unique
the number 72 is unique
the number 87 is unique
the number 75 is unique
the number 53 is unique

In [18]:
#Q6

def functionA(i):
    return i**2
    
def functionB(i):
    return i**3

def functionC(i):
    return functionB(functionA(i))
functionC(3)

729

In [19]:
#Q7A

l=[]
for i in range (0,11):
    l.append(i**3)
print(l)

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

In [20]:
#Q7B

cubed=[i**3 for i in range (0,11)]
print(cubed)

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

In [ ]:
#Q8

for a in range (1,100):
    b=a+1
    c=b+1
    while c<=100:
        while (c**2)<(a**2)+(b**2):
            c=c+1
    if (c**2)==(a**2)+(b**2) and c<=100:
        print(a,b,c)
    b=b+1

In [8]:
#Q9

import math
def Norm (x,y,z):
    d=x**2+y**2+z**2
    X=x/math.sqrt(d)
    Y=y/math.sqrt(d)
    Z=z/math.sqrt(d)
    print ((X,Y,Z))
    
    
Norm (10,10,10)

(0.5773502691896257, 0.5773502691896257, 0.5773502691896257)